name: secondary_screen_example
description: Example app demonstrating the secondary_screen package.
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  secondary_screen:
    path: ..
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
